remote_theme: pages-themes/midnight@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
description: Cybersec professional. Malware analysis and reverse engineering
avatar: "https://avatars.githubusercontent.com/u/24233481?v=4"
